# Generated by Django 4.1.7 on 2023-05-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_image_product_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('order_count', models.IntegerField(default=0)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
            ],
        ),
    ]
