# Generated by Django 4.1.7 on 2023-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_product_image_product_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryofcategories',
            name='categoryfrom',
        ),
    ]
