# Generated by Django 4.1.7 on 2023-05-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoryofcategories_categoryfrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryofcategories',
            name='categoryfrom',
        ),
    ]
