# Generated by Django 4.1.7 on 2023-05-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_product_categoryofcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryofcategories',
            name='categoryfrom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
    ]
