# Generated by Django 4.2.1 on 2023-05-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
